#!/usr/bin/python3
import sys


def first_factor(num):
    if num % 2 == 0:
        return 2
    i = 3
    while i*i <= num:
        if num % i == 0:
            return i
        i += 2
    return 1


def main():
    test_file = open(sys.argv[1], "r")
    while True:
        try:
            num = int(test_file.readline())
            factor = first_factor(num)
            print("{}={}*{}".format(num, num // factor, factor))
        except:
            break
    test_file.close()

if __name__ == "__main__":
    main()
