#!/usr/bin/python3
import sys

def first_factor(num):
    if num % 2 == 0:
        return 2
    for i in range(3, int(num ** 0.5) + 1, 2):
        if num % i == 0:
            return i
    return num


def main():
    test_file = open(sys.argv[1], "r")
    num = int(test_file.read())
    factor = first_factor(num)
    print("{}={}*{}".format(num, num // factor, factor))
    test_file.close()

if __name__ == "__main__":
    main()
